version: '3'

services:
  postgres:
    restart: always
    image: postgres:11.3-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data 
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD    
  api:
    build:
      context: ./
      dockerfile: api/Dockerfile 
    depends_on:
      - postgres
    volumes:
      - /usr/api/node_modules
      - ./api/src:/usr/api/src     
    environment:
      - POSTGRES_HOST
      - POSTGRES_PORT
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - API_SERVER_PORT
      - API_NODE_ENV
      - API_JWT_SECRET
      - SUBSCRIBER_GRPC_PORT
  subscriber:
    build:
      context: ./
      dockerfile: subscriber/Dockerfile
    depends_on:
      - api
    environment:
      - API_JWT_SECRET
      - SUBSCRIBER_GRPC_PORT
      - SUBSCRIBER_SERVER_PORT
  nginx:
    build: 
      context: ./
      dockerfile: nginx/Dockerfile
    depends_on:
      - postgres
      - api
      - subscriber
    volumes:
      - ./nginx/cfg.template:/etc/nginx/conf.d/cfg.template
    ports:
      # host:container format
      - "${NGINX_EXPOSED_PORT}:80"
    environment:
      - API_SERVER_PORT
      - SUBSCRIBER_SERVER_PORT     

volumes:
  pgdata:      
